import { Inter } from "next/font/google";
import "./globals.css";
import { CssBaseline } from "@mui/material";
import { ThemeProvider } from "./context/page";
import { AuthProvider } from "./context/authContext/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>  
     
    <html lang="en">
      <head>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
  <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet"/>
      </head>
      <body className={inter.className}>
      <CssBaseline />
    <ThemeProvider>
      <AuthProvider>
        {children}
    </AuthProvider>
    </ThemeProvider>
        </body>
    </html>
  </>
  );
}
